spring:
  application:
    name: eureka-order
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
    fetch-registry: true
    #需要将服务注册到eureka
    register-with-eureka: true
