#指定当前微服务的名称
spring:
  application:
    name: eureka-server
#指定服务端口
server:
  port: 8080
#指定eureka主机名称
eureka:
  instance:
    hostname: 127.0.0.1
  #指定eureka注册到那个服务器中
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka
    #是否将自己注册到eureka中去
    register-with-eureka: false
    #是否检索服务
    fetch-registry: false

