spring:
  application:
    name: eureka-goods
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
    fetch-registry: true
    #\u9700\u8981\u5C06\u670D\u52A1\u6CE8\u518C\u5230eureka
    register-with-eureka: true
